export type AvailabilityState = 'available' | 'occupied' | 'unavailable'

export type ActivityOwner = 'SELF' | 'USER'

export interface AvailabilityDecision {
  state: AvailabilityState
  owner: ActivityOwner
  reason: string
  evidence: string
}

const UNAVAILABLE_ZH = [
  /(?:等|等等|稍等)我(?:一下|一会儿?|片刻)/,
  /(?:等|待)我(?:回来|回來)/,
  /(?:马上|一会儿?|待会儿?|等下)(?:就)?回来/,
  /(?:出来|结束|到了|忙完)(?:就|再)?(?:找你|跟你说|回你|联系你)/,
  /(?:这会儿|现在)(?:不能|没法|不方便)(?:继续)?(?:回|聊)/,
  /等我(?:两|几|[0-9一二三四五六七八九十]+)分钟/,
]
const UNAVAILABLE_EN = /\b(?:brb|be right back|gotta go|gtg|talk (?:to you )?later|wait for me|i(?:'|’)ll be back)\b/i

const OCCUPIED_ZH = /(?:开(?:个|会儿?)?会|会议|吃饭|用餐|工作|写(?:东西|报告|稿)|看(?:电影|电视)|买东西|购物|做饭|在忙|忙工作)/
const OCCUPIED_EN = /\b(?:in a meeting|have a meeting|working|at work|eating|having (?:lunch|dinner|breakfast)|cooking|watching (?:a movie|tv)|busy)\b/i

function matchedEvidence(text: string, match: RegExpMatchArray | null): string {
  if (!match) return text.trim()
  const start = match.index ?? 0
  const sentenceStart = Math.max(text.lastIndexOf('。', start - 1), text.lastIndexOf('\n', start - 1)) + 1
  const tail = text.slice(sentenceStart)
  const end = tail.search(/[。！？!?\n]/)
  return (end >= 0 ? tail.slice(0, end + 1) : tail).trim()
}

/** Classify a reply generated by the current TA. Ownership is therefore always SELF. */
export function classifyAvailability(text: string): AvailabilityDecision {
  const value = String(text ?? '').trim()
  const unavailable = UNAVAILABLE_ZH.map((rule) => value.match(rule)).find(Boolean) ?? value.match(UNAVAILABLE_EN)
  if (unavailable) {
    return { state: 'unavailable', owner: 'SELF', reason: 'explicit_temporary_exit', evidence: matchedEvidence(value, unavailable) }
  }

  const occupied = value.match(OCCUPIED_ZH) ?? value.match(OCCUPIED_EN)
  if (occupied) {
    return { state: 'occupied', owner: 'SELF', reason: 'activity_allows_chat', evidence: matchedEvidence(value, occupied) }
  }

  return { state: 'available', owner: 'SELF', reason: 'no_explicit_exit', evidence: value }
}

const UNSUPPORTED_RECENT_ACTIONS = [
  { zh: /(?:刚|顺便|刚刚)?洗(?:了)?手/, en: /\b(?:just )?wash(?:ed)? (?:my )?hands\b/i },
  { zh: /(?:刚|顺便|刚刚)?买(?:了)?(?:杯|了杯)?咖啡/, en: /\b(?:just )?(?:bought|got) (?:a |some )?coffee\b/i },
  { zh: /(?:刚|路上|刚刚)?(?:碰到|遇到)(?:了)?朋友/, en: /\b(?:just )?(?:met|ran into) (?:a |my )?friend\b/i },
]

/** Conservative local guard for a generated Busy Return; it never invokes a model. */
export function isGroundedBusyReturn(content: string, selfActivity: string): boolean {
  const reply = String(content ?? '').trim()
  const activity = String(selfActivity ?? '').trim()
  if (!reply) return false

  for (const action of UNSUPPORTED_RECENT_ACTIONS) {
    if ((action.zh.test(reply) && !action.zh.test(activity)) || (action.en.test(reply) && !action.en.test(activity))) return false
  }

  const activityTerms = activity.match(/洗澡|冲澡|下楼|开会|汇报|开车|吃饭|做饭|工作|shower|meeting|presentation|driv(?:e|ing)|dinner|lunch/gi) ?? []
  if (activityTerms.length > 0 && /(?:你|you).{0,12}(?:洗完|开完|忙完|到了|回来|shower|meeting|presentation|driv|finish|back)/i.test(reply)) {
    return false
  }
  return true
}

export function busyReturnFallback(lang: 'zh' | 'en' = 'zh'): string {
  return lang === 'en' ? "I'm back." : '忙完了，我回来了。'
}
