import assert from 'node:assert/strict'
import fs from 'node:fs'
const account = fs.readFileSync(new URL('../src/components/Account.tsx', import.meta.url), 'utf8')
const css = fs.readFileSync(new URL('../src/index.css', import.meta.url), 'utf8')
assert.match(account, /'main' \| 'login-methods'/)
assert.match(account, /云端同步正常/)
assert.match(account, /聊天、记忆和 TA 的资料会自动同步/)
assert.match(account, /AccountGroup title="账号"/)
assert.match(account, /AccountGroup title="同步"/)
assert.match(account, /AccountGroup title="我的内容"/)
assert.match(account, /AccountGroup title="账号操作"/)
assert.match(account, /setPanel\('login-methods'\)/)
assert.match(account, /绑定另一个邮箱/)
assert.match(account, /handleSendVerify/)
assert.match(account, /void handleSync\(\)/)
assert.match(account, /void handleExport\(\)/)
assert.match(account, /void handleImportLegacy\(\)/)
assert.match(account, /DELETE_CONFIRM_WORD/)
assert.match(css, /\.account-list-card\s*\{[^}]*border-radius:\s*16px/)
assert.match(css, /\.account-delete-entry\s*\{[^}]*var\(--el-danger/)
console.log('settings account v2: PASS')
