import assert from 'node:assert/strict'
import fs from 'node:fs'

const homeCss = fs.readFileSync(new URL('../src/styles/home.css', import.meta.url), 'utf8')
const homeTsx = fs.readFileSync(new URL('../src/components/Home.tsx', import.meta.url), 'utf8')
const orbTsx = fs.readFileSync(new URL('../src/components/TaOrb.tsx', import.meta.url), 'utf8')

console.log('[P5-B] Home 内容顺序 / 文案 / 数据挂载不变')
const companionIndex = homeTsx.indexOf('className="home-companion"')
const talkIndex = homeTsx.indexOf('className="home-talk"')
const lifeIndex = homeTsx.indexOf('className="home-life"')
assert.ok(companionIndex >= 0 && talkIndex > companionIndex && lifeIndex > talkIndex)
assert.ok(homeTsx.includes('{taName} 此刻'))
assert.ok(homeTsx.includes('和 {taName} 说说话'))
assert.ok(homeTsx.includes('<TaOrb label={taName} scene={scene.id} avatar={taAvatar} />'))

console.log('[P5-B] Orb 用 CSS Faux 3D 分层，不新增 JS 跟手 / Canvas')
assert.ok(homeCss.includes('perspective: 720px;'))
assert.ok(homeCss.includes('transform-style: preserve-3d;'))
assert.ok(homeCss.includes('.ta-orb::before'))
assert.ok(homeCss.includes('.ta-orb::after'))
assert.ok(homeCss.includes('transform: rotateX(5deg) translateZ(5px);'))
assert.ok(homeCss.includes('transform: translateZ(14px);'))
assert.ok(homeCss.includes('var(--el-shadow-raised'))
assert.equal(orbTsx.includes('canvas'), false)
assert.equal(orbTsx.includes('requestAnimationFrame'), false)
assert.equal(orbTsx.includes('onPointerMove'), false)
assert.equal(orbTsx.includes('onMouseMove'), false)

console.log('[P5-B] CTA 复用 P5-A Press / Lift / Settle')
assert.ok(homeCss.includes('var(--el-motion-settle'))
assert.ok(homeCss.includes('var(--el-ease-settle'))
assert.ok(homeCss.includes('var(--el-feedback-press-transform'))
assert.ok(homeCss.includes('var(--el-feedback-lift-transform'))
assert.ok(homeCss.includes('@media (hover: hover) and (pointer: fine)'))
assert.ok(homeCss.includes('.home-talk:hover'))

console.log('[P5-B] coarse pointer 降载')
const coarseStart = homeCss.indexOf('@media (pointer: coarse)')
assert.ok(coarseStart >= 0)
const coarseEnd = homeCss.indexOf('@media (prefers-reduced-motion: reduce)', coarseStart)
const coarseBlock = homeCss.slice(coarseStart, coarseEnd)
assert.ok(coarseBlock.includes('.ta-orb-track'))
assert.ok(coarseBlock.includes('.ta-orb-dot'))
assert.ok(coarseBlock.includes('animation: none;'))
assert.ok(coarseBlock.includes('.ta-orb-core'))
assert.ok(coarseBlock.includes('animation-duration: 11s;'))

console.log('[P5-B] reduced motion 停止持续动画，CTA 不位移')
const reducedStart = homeCss.indexOf('@media (prefers-reduced-motion: reduce)', coarseEnd)
assert.ok(reducedStart >= 0)
const reducedBlock = homeCss.slice(reducedStart, homeCss.indexOf('/* ---- Home weather', reducedStart))
assert.ok(reducedBlock.includes('.ta-orb-track'))
assert.ok(reducedBlock.includes('.ta-orb-dot'))
assert.ok(reducedBlock.includes('.ta-orb-core'))
assert.ok(reducedBlock.includes('animation: none;'))
assert.ok(reducedBlock.includes('.home-talk:active'))
assert.ok(reducedBlock.includes('transform: none;'))

console.log('[P5-B] 390px 安全：3D 装饰不参与布局且小于 Orb')
assert.ok(homeCss.includes('pointer-events: none;'))
assert.ok(homeCss.includes('width: 78px;'))
assert.ok(homeCss.includes('scaleX(1.08)'))
assert.ok(78 * 1.08 < 168, '接触阴影不得超过 168px Orb 宽度')
assert.equal(homeCss.includes('width: 100vw'), false)

console.log('P5-B home presence tests passed')
