import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { initiativeCooldownMs } from '../src/lib/initiativePolicy.ts'

const listen = readFileSync('src/components/ListenTogether.tsx', 'utf8')
const listenState = readFileSync('src/lib/listenTogetherState.ts', 'utf8')
const aiSpace = readFileSync('src/components/AISpace.tsx', 'utf8')
const spaceCss = readFileSync('src/styles/space.css', 'utf8')
const settings = readFileSync('src/components/Settings.tsx', 'utf8')
const chatSettings = readFileSync('src/components/ChatSettings.tsx', 'utf8')
const home = readFileSync('src/components/Home.tsx', 'utf8')
const notificationsPage = readFileSync('src/components/NotificationsPage.tsx', 'utf8')
const app = readFileSync('src/App.tsx', 'utf8')
const storage = readFileSync('src/lib/storage.ts', 'utf8')
const systemNotification = readFileSync('src/lib/systemNotification.ts', 'utf8')
const sessionStore = readFileSync('src/lib/sessionStore.ts', 'utf8')
const rolesPage = readFileSync('src/components/RolesPage.tsx', 'utf8')
const chat = readFileSync('src/components/Chat.tsx', 'utf8')

console.log('[S5] 播放器保持本地音频，视觉为小平板 + 支架 + 有线耳机')
assert.match(listen, /accept="audio\/\*"/)
assert.match(listenState, /URL\.createObjectURL\(file\)/)
assert.match(listenState, /URL\.revokeObjectURL/)
assert.match(listenState, /current: audio\?\.currentTime/)
assert.match(listenState, /interface UserPlayerState/)
assert.doesNotMatch(listenState, /const states = new Map/)
assert.match(listenState, /播放器属于当前用户\/浏览器会话，而不是某个 TA/)
assert.match(listenState, /subscribeListenTogether\(/)
assert.match(listenState, /chooseListenTogetherTrack\(sessionId: string/)
assert.match(listenState, /chooseListenTogetherTracks\(sessionId: string, files: FileList \| File\[\]\)/)
assert.match(listenState, /stepListenTogether\(/)
assert.match(listenState, /setListenTogetherVolume\(/)
assert.match(listenState, /setListenTogetherMode\(/)
assert.match(listen, /接音乐/)
assert.match(listen, /上一首/)
assert.match(listen, /下一首/)
assert.match(listen, /音量/)
assert.match(listen, /顺序播放/)
assert.match(listen, /随机播放/)
assert.match(listen, /multiple/)
assert.doesNotMatch(listen, /listen-connect-panel/)
assert.match(aiSpace, /space-live-player-connect/) 
assert.doesNotMatch(sessionStore, /ACTIVE_SESSION_CHANGED_EVENT/)
assert.doesNotMatch(sessionStore, /dispatchEvent\(new CustomEvent\('yiwem:active-session-changed'/)
assert.doesNotMatch(listenState, /pauseListenTogether/)
assert.match(app, /function switchActiveSession\(sessionId: string\)[\s\S]{0,220}setActiveSessionId/)
assert.doesNotMatch(app, /pauseListenTogether/)
assert.doesNotMatch(rolesPage, /pauseListenTogether/)
assert.match(rolesPage, /const switchActiveSession = \(id: string\) => \{[\s\S]{0,180}setActiveSessionId\(id\)/)
assert.match(rolesPage, /const confirmSelect = \(id: string\) => \{[\s\S]{0,160}switchActiveSession\(id\)/)
assert.match(chat, /getListenTogetherSnapshot\(\)/)
assert.match(chat, /id: 'user-listening'/)
assert.match(listen, /getActiveSessionId\(\)/)
assert.match(aiSpace, /subscribeListenTogether\(sessionId, setListenSnapshot\)/)
assert.match(listen, /listen-tablet/)
assert.match(listen, /listen-stand/)
assert.match(listen, /listen-earphones/)
assert.doesNotMatch(listen + listenState, /fetch\(|axios|upload|postMessage|api\.eluvin/)
assert.match(spaceCss, /\.listen-tablet/)
assert.match(spaceCss, /\.listen-stand/)
assert.match(spaceCss, /\.listen-earphones/)

console.log('[S5] 抽屉默认保持定稿微开，点击先拉开再进入一周情书')
assert.match(aiSpace, /drawerOpening/)
assert.match(aiSpace, /openWeeklyFromDrawer/)
assert.match(aiSpace, /setDrawerOpening\(true\)/)
assert.match(aiSpace, /prefers-reduced-motion: reduce/)
assert.match(aiSpace, /onOpenWeekly\(\)/)
assert.match(aiSpace, /拉开抽屉，打开一周情书/)
assert.match(spaceCss, /is-weekly-letter\.is-opening \.space-drawer-peek/)
assert.match(spaceCss, /translate3d\(0, 48%, 0\)/)
assert.match(aiSpace, /matches \? 1 : 470/)
assert.match(aiSpace, /drawerNeedsReturn = true/)
assert.match(spaceCss, /@keyframes space-drawer-return/)
assert.doesNotMatch(spaceCss, /is-weekly-letter\.is-opening \.space-drawer-peek[\s\S]{0,120}translateY\(11px\)/)

console.log('[S5] 照片墙继续复用原链路，不另建网络图片能力')
assert.match(aiSpace, /loadLocalPhotos/)
assert.match(aiSpace, /uploadPhoto/)
assert.match(aiSpace, /deletePhoto/)
assert.match(aiSpace, /renderPhotoWall\(\)/)
assert.match(aiSpace, /const openPhotoWallFromScene = \(\) =>/)
assert.match(aiSpace, /openDeskObject\('photos', openPhotoWall\)/)
assert.doesNotMatch(aiSpace, /openPhotoWallFromScene[\s\S]{0,320}fileInputRef\.current\?\.click\(\)/)
assert.match(aiSpace, /onClick=\{openPhotoWallFromScene\}/)
assert.match(aiSpace, /scenePlacement/)
assert.match(aiSpace, /onPointerMove=/)
assert.match(aiSpace, /persistScenePhotoPlacements/)
assert.doesNotMatch(aiSpace, /https?:\/\//)

console.log('[S5] 站内信只留 Home 入口；页面标题仍是消息与通知')
assert.match(home, /站内信，有新消息/)
assert.match(home, /title="站内信"/)
assert.doesNotMatch(settings, /label="消息与通知"/)
assert.match(notificationsPage, /<h2 className="detail-title">消息与通知<\/h2>/)

console.log('[S5] 系统通知与主动消息解耦')
const supportStart = settings.indexOf('<ProfileGroup title="使用与支持">')
const supportEnd = settings.indexOf('</ProfileGroup>', supportStart)
const supportBlock = settings.slice(supportStart, supportEnd)
assert.match(supportBlock, /系统通知/)
assert.match(supportBlock, /settings-switch/)
assert.match(settings, /⚠️ios 用户：需要把忆文添加到主屏幕才能开启通知，safari 浏览器使用收不到哦/)
assert.match(storage, /isSystemNotificationEnabled/)
assert.match(storage, /saveSystemNotificationEnabled/)
assert.match(storage, /const systemNotificationEnabled = isSystemNotificationEnabled\(\)/)
assert.match(storage, /systemNotificationEnabled \? \{ systemNotificationEnabled: true \} : \{\}/)
assert.doesNotMatch(storage, /ai_companion_system_notification/)
assert.match(systemNotification, /Notification\.requestPermission\(\)/)
assert.match(systemNotification, /navigator\.serviceWorker\.getRegistration\(\)/)
assert.match(systemNotification, /registration\.showNotification/)
assert.doesNotMatch(systemNotification, /fetch\(|Bark|bark|webhook|pushplus|server酱/i)
assert.match(app, /showSystemNotification/)
assert.match(app, /有一条新消息，打开忆文看看。/)
assert.match(app, /有一件答应你的事到时间了，打开忆文看看。/)
assert.match(app, /eluvin-promise-/)
assert.doesNotMatch(app, /body:\s*content/)
assert.doesNotMatch(chatSettings, /系统通知/)

console.log('[S5] 主动消息频率 / 静默时段 / 不回应翻倍全部可用')
for (const n of [1, 2, 3, 4, 5]) assert.match(chatSettings, new RegExp(`value=\\{${n}\\}`))
assert.match(chatSettings, /quietStartHour/)
assert.match(chatSettings, /quietEndHour/)
assert.match(chatSettings, /如果你没有回应，下一次主动消息会自动隔得更久/)
assert.equal(initiativeCooldownMs(0), 6 * 60 * 60 * 1000)
assert.equal(initiativeCooldownMs(1), 12 * 60 * 60 * 1000)
assert.equal(initiativeCooldownMs(2), 24 * 60 * 60 * 1000)
assert.equal(initiativeCooldownMs(3), 48 * 60 * 60 * 1000)

console.log('[Space S5] 播放器 / 抽屉 / 照片 / 站内信 / 系统通知 / 主动消息设置 全通过')
