import assert from 'node:assert/strict'
import fs from 'node:fs'

const app = fs.readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const ui2 = fs.readFileSync(new URL('../src/styles/ui2.css', import.meta.url), 'utf8')
const home = fs.readFileSync(new URL('../src/styles/home.css', import.meta.url), 'utf8')

console.log('[P5-E] Carry only wraps persistent primary views')
assert.match(app, /function isNavView\(v: View\): boolean \{[\s\S]*v === 'home'[\s\S]*v === 'aispace'[\s\S]*v === 'settings'[\s\S]*v === 'memory'/)
assert.doesNotMatch(
  app.slice(app.indexOf('function isNavView'), app.indexOf('function navTabActive')),
  /v === 'chat'/,
  'Chat must stay out of P5-E Carry until P5-F',
)
assert.match(app, /function commitPrimaryViewWithCarry/)
assert.match(app, /!isNavView\(from\) \|\| !isNavView\(to\)/)
assert.match(app, /document\.visibilityState !== 'visible'/)
assert.match(app, /prefers-reduced-motion: reduce/)
assert.match(app, /doc\.startViewTransition/)
assert.match(app, /flushSync\(commitOnce\)/)
assert.match(app, /let committed = false/)
assert.match(app, /if \(committed\) return/)

console.log('[P5-E] normal navigation semantics remain immediate and stale-safe')
assert.match(app, /const carryRevisionRef = useRef\(0\)/)
assert.match(app, /const carryRevision = \+\+carryRevisionRef\.current[\s\S]*viewRef\.current = v[\s\S]*commitPrimaryViewWithCarry\(from, v/)
assert.match(app, /carryRevisionRef\.current \+= 1[\s\S]*viewRef\.current = v[\s\S]*setView\(v\)/, 'replaceView must cancel stale Carry without animating flow navigation')
assert.match(app, /const carryRevision = \+\+carryRevisionRef\.current[\s\S]*viewRef\.current = target[\s\S]*commitPrimaryViewWithCarry\(from, target/)
const replaceStart = app.indexOf('const replaceView = useCallback')
const replaceEnd = app.indexOf('// 挂载时初始化历史 state', replaceStart)
assert.ok(replaceStart >= 0 && replaceEnd > replaceStart)
assert.doesNotMatch(app.slice(replaceStart, replaceEnd), /commitPrimaryViewWithCarry/, 'flow replaceView stays instant')

console.log('[P5-E] Carry keeps the shell while only app-main transitions')
assert.ok(ui2.includes('.app-main {\n  view-transition-name: el-main;'))
assert.ok(ui2.includes('::view-transition-old(root)'))
assert.ok(ui2.includes('animation: none;\n  opacity: 0;'))
assert.ok(ui2.includes('::view-transition-old(el-main)'))
assert.ok(ui2.includes('::view-transition-new(el-main)'))
assert.ok(ui2.includes('@keyframes el-carry-out'))
assert.ok(ui2.includes('@keyframes el-carry-in'))
assert.equal(ui2.includes('translateX('), false, 'Carry must not introduce horizontal motion / overflow risk')

console.log('[P5-E] coarse pointer keeps lighter continuity; reduced-motion removes Carry motion')
const carryStart = ui2.indexOf('P5-E · Carry')
assert.ok(carryStart >= 0)
const carry = ui2.slice(carryStart)
const coarseStart = carry.indexOf('@media (pointer: coarse)')
const reducedStart = carry.indexOf('@media (prefers-reduced-motion: reduce)')
assert.ok(coarseStart >= 0 && reducedStart > coarseStart)
const coarse = carry.slice(coarseStart, reducedStart)
assert.ok(coarse.includes('el-carry-fade-out'))
assert.ok(coarse.includes('el-carry-fade-in'))
assert.equal(coarse.includes('translateY('), false, 'coarse Carry is opacity-only')
const reduced = carry.slice(reducedStart)
assert.ok(reduced.includes('view-transition-name: none;'))
assert.ok(reduced.includes('animation: none !important;'))

console.log('[P5-E] page visibility explicitly pauses existing continuous ambience')
assert.match(app, /data-el-page-hidden/)
assert.match(app, /document\.addEventListener\('visibilitychange', syncVisibility\)/)
assert.match(app, /document\.removeEventListener\('visibilitychange', syncVisibility\)/)
assert.match(home, /html\[data-el-page-hidden='true'\] \.ta-orb-track/)
assert.match(home, /html\[data-el-page-hidden='true'\] \.home-weather-atmosphere \*/)
assert.match(home, /animation-play-state: paused !important;/)

console.log('[P5-E] coarse pointer lowers ambient cost without deleting weather')
const homeCoarseStart = home.indexOf('@media (pointer: coarse)')
const homeReducedStart = home.indexOf('@media (prefers-reduced-motion: reduce)', homeCoarseStart)
assert.ok(homeCoarseStart >= 0 && homeReducedStart > homeCoarseStart)
const homeCoarse = home.slice(homeCoarseStart, homeReducedStart)
assert.ok(homeCoarse.includes('.ta-orb-track'))
assert.ok(homeCoarse.includes('.home-weather-rain-drop.layer-2'))
assert.ok(homeCoarse.includes('display: none;'))
assert.ok(homeCoarse.includes('animation-duration: 28s;'))
assert.ok(homeCoarse.includes('animation-duration: 11s;'))
assert.ok(homeCoarse.includes('animation-duration: 12s;'))
assert.equal(homeCoarse.includes('.home-weather-rain-drop.layer-0'), false, 'near rain remains visible on coarse pointers')
assert.equal(homeCoarse.includes('.home-weather-rain-drop.layer-1'), false, 'mid rain remains visible on coarse pointers')

console.log('[P5-E] no JS frame loop / animation library added')
const carryHelperStart = app.indexOf('function commitPrimaryViewWithCarry')
const carryHelperEnd = app.indexOf('function navTabActive', carryHelperStart)
const carryHelper = app.slice(carryHelperStart, carryHelperEnd)
assert.equal(carryHelper.includes('requestAnimationFrame'), false)
assert.equal(carryHelper.includes('setInterval'), false)
assert.equal(carryHelper.includes('setTimeout'), false)

console.log('P5-E Carry / Ambient closure tests passed')
